name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    env:
      PROJECT_NAME: "personal-website"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/ -v || echo "No tests found, skipping."

  deploy:
    runs-on: self-hosted
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Write env file
        run: |
          echo "AI_SERVER_API_KEY=${{ secrets.AI_SERVER_API_KEY }}" > .env
          echo "AI_BASE_URL=${{ secrets.AI_BASE_URL }}" >> .env
          echo "LOGFIRE_TOKEN=${{ secrets.LOGFIRE_TOKEN }}" >> .env
          echo "NTFY_TOPIC=${{ secrets.NTFY_TOPIC }}" >> .env
          echo "LOKI_URL=${{ secrets.LOKI_URL }}" >> .env

      - name: Build and restart services
        env:
            DOCKER_BUILDKIT: 1
        run: |
          docker compose down
          docker compose build --no-cache
          docker compose up -d
          docker compose ps
